import type { User, Order, Message, Transaction, DashboardStats, Bid, SalesAgentCustomer } from "./types"

// Mock users for different roles
export const mockUsers: Record<string, User> = {
  writer1: {
    id: "writer1",
    email: "writer@example.com",
    role: "writer",
    firstName: "John",
    lastName: "Writer",
    phone: "+1234567890",
    isActive: true,
    createdAt: new Date("2024-01-01"),
  },
  customer1: {
    id: "customer1",
    email: "customer@example.com",
    role: "customer",
    firstName: "Jane",
    lastName: "Customer",
    isActive: true,
    createdAt: new Date("2024-01-15"),
  },
  admin1: {
    id: "admin1",
    email: "admin@example.com",
    role: "admin",
    firstName: "Admin",
    lastName: "User",
    isActive: true,
    createdAt: new Date("2023-01-01"),
  },
  sales1: {
    id: "sales1",
    email: "sales@example.com",
    role: "sales_agent",
    firstName: "Mark",
    lastName: "Sales",
    isActive: true,
    createdAt: new Date("2023-06-01"),
  },
  editor1: {
    id: "editor1",
    email: "editor@example.com",
    role: "editor",
    firstName: "Sarah",
    lastName: "Editor",
    isActive: true,
    createdAt: new Date("2023-08-01"),
  },
  manager1: {
    id: "manager1",
    email: "manager@example.com",
    role: "writer_manager",
    firstName: "Mike",
    lastName: "Manager",
    isActive: true,
    createdAt: new Date("2023-03-01"),
  },
}

// Mock orders
export const mockOrders: Order[] = [
  {
    id: "1",
    orderNumber: "10151816",
    customerId: "customer1",
    writerId: "writer1",
    editorId: "editor1",
    salesAgentId: "sales1",
    writerManagerId: "manager1",
    title: "recordkeeping",
    topic: "recordkeeping",
    description:
      "For this week's assignment you will be taking an inventory of the information systems in your organization...",
    type: "PowerPoint presentation with speaker notes",
    educationLevel: "College",
    subject: "Nursing",
    pagesOrSlides: 15,
    words: 4125,
    sourcesRequired: 3,
    citationStyle: "APA 7th edition",
    language: "English (US)",
    spacing: "double spacing",
    totalAmount: 193.4,
    amountPaid: 0,
    currency: "KES",
    status: "in_progress",
    deadline: new Date("2024-12-09T02:29:00"),
    startedAt: new Date("2024-12-05T11:05:00"),
    isRevision: false,
    isOverdue: true,
    customerIsReturning: false,
    createdAt: new Date("2024-12-05T11:05:00"),
    updatedAt: new Date("2024-12-05T11:05:00"),
  },
  {
    id: "2",
    orderNumber: "10151817",
    customerId: "customer1",
    status: "available",
    title: "Business Ethics Analysis",
    topic: "Ethics in Modern Business",
    description: "Analyze ethical challenges in contemporary business practices...",
    type: "Research Paper",
    educationLevel: "Masters",
    subject: "Business Ethics",
    pagesOrSlides: 10,
    words: 2750,
    sourcesRequired: 8,
    citationStyle: "APA 7th edition",
    language: "English (US)",
    spacing: "double spacing",
    totalAmount: 275.5,
    amountPaid: 275.5,
    currency: "USD",
    deadline: new Date("2024-12-15T23:59:00"),
    isRevision: false,
    isOverdue: false,
    customerIsReturning: false,
    createdAt: new Date("2024-12-01T08:30:00"),
    updatedAt: new Date("2024-12-01T08:30:00"),
  },
  {
    id: "3",
    orderNumber: "10151818",
    customerId: "customer1",
    writerId: "writer1",
    status: "in_review",
    title: "Climate Change Impact Study",
    topic: "Environmental Science",
    description: "Comprehensive study on climate change effects on coastal ecosystems...",
    type: "Research Paper",
    educationLevel: "PhD",
    subject: "Environmental Science",
    pagesOrSlides: 20,
    words: 5500,
    sourcesRequired: 15,
    citationStyle: "APA 7th edition",
    language: "English (US)",
    spacing: "double spacing",
    totalAmount: 550.0,
    amountPaid: 550.0,
    currency: "USD",
    deadline: new Date("2024-12-20T23:59:00"),
    startedAt: new Date("2024-12-03T10:00:00"),
    submittedAt: new Date("2024-12-06T14:30:00"),
    isRevision: false,
    isOverdue: false,
    customerIsReturning: true,
    createdAt: new Date("2024-12-03T10:00:00"),
    updatedAt: new Date("2024-12-06T14:30:00"),
  },
  {
    id: "4",
    orderNumber: "10151820",
    customerId: "customer1",
    salesAgentId: "sales1",
    status: "available",
    title: "Machine Learning Algorithm Implementation",
    topic: "Artificial Intelligence",
    description:
      "Implement and compare three machine learning algorithms for image classification. Include detailed documentation of the methodology, results analysis, and performance metrics. Code must be well-commented and follow best practices.",
    type: "Research Paper with Code",
    educationLevel: "Masters",
    subject: "Computer Science",
    pagesOrSlides: 12,
    words: 3300,
    sourcesRequired: 10,
    citationStyle: "IEEE",
    language: "English (US)",
    spacing: "double spacing",
    totalAmount: 420.0,
    amountPaid: 420.0,
    currency: "USD",
    deadline: new Date("2024-12-22T23:59:00"),
    isRevision: false,
    isOverdue: false,
    customerIsReturning: false,
    createdAt: new Date("2024-12-07T09:15:00"),
    updatedAt: new Date("2024-12-07T09:15:00"),
  },
  {
    id: "5",
    orderNumber: "10151821",
    customerId: "customer1",
    salesAgentId: "sales1",
    status: "available",
    title: "Marketing Strategy for Tech Startup",
    topic: "Digital Marketing",
    description:
      "Develop a comprehensive marketing strategy for a SaaS startup targeting small businesses. Include market analysis, competitor research, target audience definition, channel strategy, and budget allocation with ROI projections.",
    type: "Business Plan",
    educationLevel: "MBA",
    subject: "Marketing",
    pagesOrSlides: 25,
    words: 6875,
    sourcesRequired: 12,
    citationStyle: "APA 7th edition",
    language: "English (US)",
    spacing: "double spacing",
    totalAmount: 687.5,
    amountPaid: 687.5,
    currency: "USD",
    deadline: new Date("2024-12-25T23:59:00"),
    isRevision: false,
    isOverdue: false,
    customerIsReturning: true,
    createdAt: new Date("2024-12-08T10:00:00"),
    updatedAt: new Date("2024-12-08T10:00:00"),
  },
  {
    id: "6",
    orderNumber: "10151822",
    customerId: "customer1",
    status: "available",
    title: "Nursing Care Plan for Diabetes Patients",
    topic: "Healthcare Management",
    description:
      "Create a detailed nursing care plan for type 2 diabetes patients including assessment, diagnosis, planning, implementation, and evaluation phases. Must include evidence-based interventions and patient education strategies.",
    type: "Case Study",
    educationLevel: "College",
    subject: "Nursing",
    pagesOrSlides: 8,
    words: 2200,
    sourcesRequired: 6,
    citationStyle: "APA 7th edition",
    language: "English (US)",
    spacing: "double spacing",
    totalAmount: 176.0,
    amountPaid: 176.0,
    currency: "USD",
    deadline: new Date("2024-12-18T23:59:00"),
    isRevision: false,
    isOverdue: false,
    customerIsReturning: false,
    createdAt: new Date("2024-12-08T14:20:00"),
    updatedAt: new Date("2024-12-08T14:20:00"),
  },
  {
    id: "7",
    orderNumber: "10151823",
    customerId: "customer1",
    salesAgentId: "sales1",
    status: "available",
    title: "Financial Statement Analysis of Fortune 500 Company",
    topic: "Corporate Finance",
    description:
      "Conduct a comprehensive financial analysis of a Fortune 500 company using the last 3 years of financial statements. Include ratio analysis, trend analysis, and comparison with industry benchmarks. Provide investment recommendations.",
    type: "Financial Report",
    educationLevel: "Masters",
    subject: "Finance",
    pagesOrSlides: 15,
    words: 4125,
    sourcesRequired: 15,
    citationStyle: "Harvard",
    language: "English (US)",
    spacing: "double spacing",
    totalAmount: 495.0,
    amountPaid: 495.0,
    currency: "USD",
    deadline: new Date("2024-12-20T23:59:00"),
    isRevision: false,
    isOverdue: false,
    customerIsReturning: false,
    createdAt: new Date("2024-12-08T16:45:00"),
    updatedAt: new Date("2024-12-08T16:45:00"),
  },
  {
    id: "8",
    orderNumber: "10151824",
    customerId: "customer1",
    status: "available",
    title: "Shakespearean Literary Analysis",
    topic: "English Literature",
    description:
      "Analyze the themes of power and corruption in Shakespeare's Macbeth. Discuss how these themes are developed through character development, symbolism, and dramatic techniques. Include close reading of key passages.",
    type: "Essay",
    educationLevel: "College",
    subject: "Literature",
    pagesOrSlides: 6,
    words: 1650,
    sourcesRequired: 5,
    citationStyle: "MLA",
    language: "English (US)",
    spacing: "double spacing",
    totalAmount: 99.0,
    amountPaid: 99.0,
    currency: "USD",
    deadline: new Date("2024-12-16T23:59:00"),
    isRevision: false,
    isOverdue: false,
    customerIsReturning: false,
    createdAt: new Date("2024-12-09T08:00:00"),
    updatedAt: new Date("2024-12-09T08:00:00"),
  },
]

// Mock messages
export const mockMessages: Message[] = [
  {
    id: "1",
    orderId: "1",
    senderId: "customer1",
    receiverId: "writer1",
    messageText:
      "Hi, I am reaching out to express my interest in assisting with your assignment. With my experience in your field, I am confident in my ability to deliver high-quality work on time, maintain clear communication throughout, provide revisions if needed, and prioritize your complete satisfaction. I look forward to the opportunity to work together. Thank you!",
    isRead: true,
    readAt: new Date("2024-12-05T11:04:00"),
    createdAt: new Date("2024-12-05T11:04:00"),
  },
  {
    id: "2",
    orderId: "1",
    senderId: "writer1",
    receiverId: "customer1",
    messageText: "Thanks for the invite.",
    isRead: true,
    readAt: new Date("2024-12-05T11:05:00"),
    createdAt: new Date("2024-12-05T11:05:00"),
  },
  {
    id: "3",
    orderId: "1",
    senderId: "customer1",
    receiverId: "writer1",
    messageText:
      "Received with thanks. Could you please confirm whether there is a required textbook for the course, or if a rubric or assignment template has been provided?",
    isRead: true,
    readAt: new Date("2024-12-05T11:05:00"),
    createdAt: new Date("2024-12-05T11:05:00"),
  },
]

// Mock dashboard stats for writer
export const mockWriterStats: DashboardStats = {
  available: 6,
  inProgress: 0,
  inReview: 1,
  revision: 1,
  disputed: 4,
  completedPaid: 11,
  completedUnpaid: 0,
  totalEarnings: 35135,
}

// Mock transactions
export const mockTransactions: Transaction[] = [
  {
    id: "1",
    orderId: "3",
    userId: "writer1",
    transactionType: "writer_earning",
    amount: 247.5,
    currency: "USD",
    description: "Payment for Order #10151818 - Climate Change Impact Study",
    status: "completed",
    createdAt: new Date("2024-12-06T15:00:00"),
  },
  {
    id: "2",
    orderId: "1",
    userId: "writer1",
    transactionType: "writer_earning",
    amount: 77.36,
    currency: "KES",
    description: "Payment for Order #10151816 - recordkeeping (Pending)",
    status: "pending",
    createdAt: new Date("2024-12-05T11:05:00"),
  },
  {
    id: "3",
    orderId: "4",
    userId: "sales1",
    transactionType: "sales_commission",
    amount: 42.0,
    currency: "USD",
    description: "10% Commission for New Customer - Order #10151820",
    status: "completed",
    createdAt: new Date("2024-12-07T10:00:00"),
  },
  {
    id: "4",
    orderId: "5",
    userId: "sales1",
    transactionType: "sales_commission",
    amount: 34.38,
    currency: "USD",
    description: "5% Commission for Returning Customer - Order #10151821",
    status: "completed",
    createdAt: new Date("2024-12-08T11:00:00"),
  },
  {
    id: "5",
    orderId: "7",
    userId: "sales1",
    transactionType: "sales_commission",
    amount: 49.5,
    currency: "USD",
    description: "10% Commission for New Customer - Order #10151823",
    status: "pending",
    createdAt: new Date("2024-12-08T17:00:00"),
  },
]

// Mock bids for the bidding system
export const mockBids: Bid[] = [
  {
    id: "bid1",
    orderId: "2",
    writerId: "writer1",
    bidAmount: 110.2,
    currency: "USD",
    proposedDeadline: new Date("2024-12-15T20:00:00"),
    coverLetter:
      "I have extensive experience in business ethics and have completed similar projects. I can deliver high-quality work before the deadline.",
    status: "pending",
    createdAt: new Date("2024-12-02T10:00:00"),
  },
]

// Mock order bids with extended bid information for customer view
export const mockOrderBids = [
  {
    id: "bid1",
    orderId: "2",
    writerId: "writer1",
    writerName: "John Writer",
    writerRating: 4.8,
    completedOrders: 127,
    bidAmount: 110.2,
    deliveryTime: 48,
    coverLetter:
      "I have extensive experience in business ethics and have completed similar projects. I can deliver high-quality work before the deadline.",
    status: "pending",
    createdAt: new Date("2024-12-02T10:00:00"),
  },
  {
    id: "bid2",
    orderId: "2",
    writerId: "writer2",
    writerName: "Sarah Mitchell",
    writerRating: 4.9,
    completedOrders: 203,
    bidAmount: 120.0,
    deliveryTime: 36,
    coverLetter:
      "Masters degree in Business Administration with specialization in Ethics. I've written 50+ papers on business ethics topics.",
    status: "pending",
    createdAt: new Date("2024-12-02T11:30:00"),
  },
  {
    id: "bid3",
    orderId: "4",
    writerId: "writer3",
    writerName: "David Chen",
    writerRating: 5.0,
    completedOrders: 89,
    bidAmount: 400.0,
    deliveryTime: 72,
    coverLetter:
      "PhD in Computer Science with expertise in ML algorithms. I can implement the algorithms in Python with comprehensive documentation.",
    status: "pending",
    createdAt: new Date("2024-12-07T10:00:00"),
  },
  {
    id: "bid4",
    orderId: "5",
    writerId: "writer1",
    writerName: "John Writer",
    writerRating: 4.8,
    completedOrders: 127,
    bidAmount: 650.0,
    deliveryTime: 96,
    coverLetter:
      "I have created marketing strategies for multiple tech startups. My plans include detailed market research and actionable tactics.",
    status: "pending",
    createdAt: new Date("2024-12-08T11:00:00"),
  },
  {
    id: "bid5",
    orderId: "6",
    writerId: "writer4",
    writerName: "Emily Rodriguez",
    writerRating: 4.7,
    completedOrders: 156,
    bidAmount: 160.0,
    deliveryTime: 24,
    coverLetter:
      "Registered Nurse with 8 years of experience. I specialize in creating evidence-based nursing care plans.",
    status: "pending",
    createdAt: new Date("2024-12-08T15:00:00"),
  },
  {
    id: "bid6",
    orderId: "7",
    writerId: "writer5",
    writerName: "Michael Thompson",
    writerRating: 4.9,
    completedOrders: 178,
    bidAmount: 480.0,
    deliveryTime: 60,
    coverLetter:
      "CFA charterholder with experience in financial analysis. I've analyzed Fortune 500 companies extensively.",
    status: "pending",
    createdAt: new Date("2024-12-08T17:00:00"),
  },
  {
    id: "bid7",
    orderId: "8",
    writerId: "writer1",
    writerName: "John Writer",
    writerRating: 4.8,
    completedOrders: 127,
    bidAmount: 95.0,
    deliveryTime: 30,
    coverLetter:
      "English Literature graduate with focus on Shakespeare. I've written numerous analyses of Macbeth's themes.",
    status: "pending",
    createdAt: new Date("2024-12-09T09:00:00"),
  },
]

// Mock sales agent customers
export const mockSalesAgentCustomers: SalesAgentCustomer[] = [
  {
    id: "customer1",
    name: "Jane Customer",
    email: "customer@example.com",
    referralCode: "MARK2023",
    status: "returning",
    totalOrders: 8,
    totalSpent: 3245.5,
    commissionEarned: 262.28,
    joinedDate: new Date("2024-01-15"),
    lastOrderDate: new Date("2024-12-08"),
  },
  {
    id: "customer2",
    name: "Robert Johnson",
    email: "robert.j@example.com",
    referralCode: "MARK2023",
    status: "new",
    totalOrders: 2,
    totalSpent: 550.0,
    commissionEarned: 55.0,
    joinedDate: new Date("2024-11-20"),
    lastOrderDate: new Date("2024-12-05"),
  },
  {
    id: "customer3",
    name: "Emily Davis",
    email: "emily.d@example.com",
    referralCode: "MARK2023",
    status: "returning",
    totalOrders: 12,
    totalSpent: 4890.0,
    commissionEarned: 394.5,
    joinedDate: new Date("2023-09-10"),
    lastOrderDate: new Date("2024-12-07"),
  },
  {
    id: "customer4",
    name: "Michael Brown",
    email: "michael.b@example.com",
    referralCode: "MARK2023",
    status: "new",
    totalOrders: 1,
    totalSpent: 275.5,
    commissionEarned: 27.55,
    joinedDate: new Date("2024-12-01"),
    lastOrderDate: new Date("2024-12-01"),
  },
  {
    id: "customer5",
    name: "Sarah Wilson",
    email: "sarah.w@example.com",
    referralCode: "MARK2023",
    status: "returning",
    totalOrders: 15,
    totalSpent: 5670.0,
    commissionEarned: 458.85,
    joinedDate: new Date("2023-07-22"),
    lastOrderDate: new Date("2024-12-06"),
  },
]

// Function to get available orders (excluding ones already bid on by the writer)
export function getAvailableOrders(writerId: string): Order[] {
  const writerBidOrderIds = mockBids.filter((bid) => bid.writerId === writerId).map((bid) => bid.orderId)

  return mockOrders.filter((order) => order.status === "available" && !writerBidOrderIds.includes(order.id))
}

// Function to get writer's bids
export function getWriterBids(writerId: string): Bid[] {
  return mockBids.filter((bid) => bid.writerId === writerId)
}

// Function to get sales agent stats
export function getSalesAgentStats(agentId: string) {
  const customers = mockSalesAgentCustomers
  const transactions = mockTransactions.filter((t) => t.userId === agentId && t.transactionType === "sales_commission")

  const totalCustomers = customers.length
  const newCustomers = customers.filter((c) => c.status === "new").length
  const returningCustomers = customers.filter((c) => c.status === "returning").length
  const activeCustomers = customers.filter((c) => {
    const daysSinceLastOrder = c.lastOrderDate
      ? Math.floor((Date.now() - c.lastOrderDate.getTime()) / (1000 * 60 * 60 * 24))
      : 999
    return daysSinceLastOrder < 30
  }).length

  const totalCommission = transactions.filter((t) => t.status === "completed").reduce((sum, t) => sum + t.amount, 0)
  const pendingCommission = transactions.filter((t) => t.status === "pending").reduce((sum, t) => sum + t.amount, 0)

  const totalOrders = customers.reduce((sum, c) => sum + c.totalOrders, 0)
  const totalRevenue = customers.reduce((sum, c) => sum + c.totalSpent, 0)

  return {
    totalCustomers,
    newCustomers,
    returningCustomers,
    activeCustomers,
    totalCommission,
    pendingCommission,
    totalOrders,
    totalRevenue,
    conversionRate: totalCustomers > 0 ? (returningCustomers / totalCustomers) * 100 : 0,
  }
}
